version: "3.6"

volumes:
  postgres_data:

x-app:
  &app
  build:
    context: .
    dockerfile: Dockerfile
  image: melp/api
  restart: always
  env_file:
    - .env
  volumes:
    - ./app:/usr/src/app
  command: ["bash", "-c", "/usr/src/bin/entrypoint.sh"]  

services:
  api:
    <<: *app
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db      

  db:
    image: postgis/postgis:12-2.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
  